# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rdavi\Dropbox\ARL Project\Calculation\codes\guiProgram\GuiStuff.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib.pyplot as plt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(827, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Plot = QtWidgets.QGraphicsView(self.centralwidget)
        self.Plot.setGeometry(QtCore.QRect(400, 40, 381, 461))
        self.Plot.setObjectName("Plot")
        plt.xlabel('TBD')
        plt.ylabel('TBD')
        plt.show()
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 381, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.Subsystem1 = QtWidgets.QWidget()
        self.Subsystem1.setObjectName("Subsystem1")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Subsystem1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 20, 321, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 6, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 5, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 7, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 4, 1, 1, 1)
        self.lineEdit_Time = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Time.setText("")
        self.lineEdit_Time.setObjectName("lineEdit_Time")
        self.gridLayout_2.addWidget(self.lineEdit_Time, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 7, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 3, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 1, 1, 1)
        self.lineEdit_Cost_Increment = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Cost_Increment.setObjectName("lineEdit_Cost_Increment")
        self.gridLayout_2.addWidget(self.lineEdit_Cost_Increment, 1, 3, 1, 1)
        self.lineEdit_Reliablility_Investment = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Reliablility_Investment.setObjectName("lineEdit_Reliablility_Investment")
        self.gridLayout_2.addWidget(self.lineEdit_Reliablility_Investment, 2, 3, 1, 1)
        self.lineEdit_B_Mode = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_B_Mode.setObjectName("lineEdit_B_Mode")
        self.gridLayout_2.addWidget(self.lineEdit_B_Mode, 3, 3, 1, 1)
        self.lineEdit_FEF = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_FEF.setObjectName("lineEdit_FEF")
        self.gridLayout_2.addWidget(self.lineEdit_FEF, 4, 3, 1, 1)
        self.lineEdit_A_Mode_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_A_Mode_2.setObjectName("lineEdit_A_Mode_2")
        self.gridLayout_2.addWidget(self.lineEdit_A_Mode_2, 5, 3, 1, 1)
        self.lineEdit_Initial_Cost = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Initial_Cost.setObjectName("lineEdit_Initial_Cost")
        self.gridLayout_2.addWidget(self.lineEdit_Initial_Cost, 6, 3, 1, 1)
        self.lineEdit_Operating_Cost = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Operating_Cost.setObjectName("lineEdit_Operating_Cost")
        self.gridLayout_2.addWidget(self.lineEdit_Operating_Cost, 7, 3, 1, 1)
        self.tabWidget.addTab(self.Subsystem1, "")
        self.Subsystem2 = QtWidgets.QWidget()
        self.Subsystem2.setObjectName("Subsystem2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.Subsystem2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 321, 461))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 6, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 6, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 5, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 7, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 2, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem13, 4, 1, 1, 1)
        self.lineEdit_Time_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Time_2.setText("")
        self.lineEdit_Time_2.setObjectName("lineEdit_Time_2")
        self.gridLayout_3.addWidget(self.lineEdit_Time_2, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 4, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 5, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 7, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 3, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 2, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem14, 3, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem15, 1, 1, 1, 1)
        self.lineEdit_Cost_Increment_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Cost_Increment_2.setObjectName("lineEdit_Cost_Increment_2")
        self.gridLayout_3.addWidget(self.lineEdit_Cost_Increment_2, 1, 3, 1, 1)
        self.lineEdit_Reliablility_Investment_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Reliablility_Investment_2.setObjectName("lineEdit_Reliablility_Investment_2")
        self.gridLayout_3.addWidget(self.lineEdit_Reliablility_Investment_2, 2, 3, 1, 1)
        self.lineEdit_B_Mode_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_Mode_2.setObjectName("lineEdit_B_Mode_2")
        self.gridLayout_3.addWidget(self.lineEdit_B_Mode_2, 3, 3, 1, 1)
        self.lineEdit_FEF_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_FEF_2.setObjectName("lineEdit_FEF_2")
        self.gridLayout_3.addWidget(self.lineEdit_FEF_2, 4, 3, 1, 1)
        self.lineEdit_A_Mode_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_A_Mode_3.setObjectName("lineEdit_A_Mode_3")
        self.gridLayout_3.addWidget(self.lineEdit_A_Mode_3, 5, 3, 1, 1)
        self.lineEdit_Initial_Cost_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Initial_Cost_2.setObjectName("lineEdit_Initial_Cost_2")
        self.gridLayout_3.addWidget(self.lineEdit_Initial_Cost_2, 6, 3, 1, 1)
        self.lineEdit_Operating_Cost_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Operating_Cost_2.setObjectName("lineEdit_Operating_Cost_2")
        self.gridLayout_3.addWidget(self.lineEdit_Operating_Cost_2, 7, 3, 1, 1)
        self.tabWidget.addTab(self.Subsystem2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Operating Cost"))
        self.label_5.setText(_translate("MainWindow", "Cost Increment"))
        self.label_6.setText(_translate("MainWindow", "Input Reliablity Investment"))
        self.label_8.setText(_translate("MainWindow", "Initial Cost"))
        self.label.setText(_translate("MainWindow", "Total Time"))
        self.label_2.setText(_translate("MainWindow", "Input A-Mode Failure Rate"))
        self.label_4.setText(_translate("MainWindow", "B-Mode Fix-Effectiveness Factor"))
        self.label_3.setText(_translate("MainWindow", "Input B-Mode Failure Rate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Subsystem1), _translate("MainWindow", "Tab 1"))
        self.label_9.setText(_translate("MainWindow", "Operating Cost"))
        self.label_10.setText(_translate("MainWindow", "Cost Increment"))
        self.label_11.setText(_translate("MainWindow", "Input Reliablity Investment"))
        self.label_12.setText(_translate("MainWindow", "Initial Cost"))
        self.label_13.setText(_translate("MainWindow", "Total Time"))
        self.label_14.setText(_translate("MainWindow", "Input A-Mode Failure Rate"))
        self.label_15.setText(_translate("MainWindow", "B-Mode Fix-Effectiveness Factor"))
        self.label_16.setText(_translate("MainWindow", "Input B-Mode Failure Rate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Subsystem2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

