# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiStuff.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1096, 724)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 220, 381, 461))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.Component1 = QtWidgets.QWidget()
        self.Component1.setObjectName("Component1")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Component1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 331, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.lineEdit_Ma_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Ma_1.setObjectName("lineEdit_Ma_1")
        self.gridLayout_2.addWidget(self.lineEdit_Ma_1, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 1, 1, 1)
        self.lineEdit_Mb_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Mb_1.setObjectName("lineEdit_Mb_1")
        self.gridLayout_2.addWidget(self.lineEdit_Mb_1, 2, 3, 1, 1)
        self.lineEdit_L_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_L_1.setText("")
        self.lineEdit_L_1.setObjectName("lineEdit_L_1")
        self.gridLayout_2.addWidget(self.lineEdit_L_1, 0, 3, 1, 1)
        self.lineEdit_mud_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_mud_1.setObjectName("lineEdit_mud_1")
        self.gridLayout_2.addWidget(self.lineEdit_mud_1, 3, 3, 1, 1)
        self.lineEdit_mub_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_mub_1.setObjectName("lineEdit_mub_1")
        self.gridLayout_2.addWidget(self.lineEdit_mub_1, 4, 3, 1, 1)
        self.lineEdit_c1_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_c1_1.setObjectName("lineEdit_c1_1")
        self.gridLayout_2.addWidget(self.lineEdit_c1_1, 5, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 6, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 1)
        self.lineEdit_c0_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_c0_1.setObjectName("lineEdit_c0_1")
        self.gridLayout_2.addWidget(self.lineEdit_c0_1, 6, 3, 1, 1)
        self.lineEdit_MTTRi_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_MTTRi_1.setObjectName("lineEdit_MTTRi_1")
        self.gridLayout_2.addWidget(self.lineEdit_MTTRi_1, 7, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 7, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 5, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 7, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 2, 1, 1)
        self.tabWidget.addTab(self.Component1, "")
        self.Component2 = QtWidgets.QWidget()
        self.Component2.setObjectName("Component2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.Component2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 331, 411))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 1, 1, 1, 1)
        self.lineEdit_Ma_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Ma_2.setObjectName("lineEdit_Ma_2")
        self.gridLayout_3.addWidget(self.lineEdit_Ma_2, 1, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 3, 1, 1, 1)
        self.lineEdit_Mb_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Mb_2.setObjectName("lineEdit_Mb_2")
        self.gridLayout_3.addWidget(self.lineEdit_Mb_2, 2, 3, 1, 1)
        self.lineEdit_L_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_L_2.setText("")
        self.lineEdit_L_2.setObjectName("lineEdit_L_2")
        self.gridLayout_3.addWidget(self.lineEdit_L_2, 0, 3, 1, 1)
        self.lineEdit_mud_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_mud_2.setObjectName("lineEdit_mud_2")
        self.gridLayout_3.addWidget(self.lineEdit_mud_2, 3, 3, 1, 1)
        self.lineEdit_mub_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_mub_2.setObjectName("lineEdit_mub_2")
        self.gridLayout_3.addWidget(self.lineEdit_mub_2, 4, 3, 1, 1)
        self.lineEdit_c1_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_c1_2.setObjectName("lineEdit_c1_2")
        self.gridLayout_3.addWidget(self.lineEdit_c1_2, 5, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 6, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 3, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 2, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem13, 5, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem14, 6, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 4, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 2, 1, 1)
        self.lineEdit_c0_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_c0_2.setObjectName("lineEdit_c0_2")
        self.gridLayout_3.addWidget(self.lineEdit_c0_2, 6, 3, 1, 1)
        self.lineEdit_MTTRi_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_MTTRi_2.setObjectName("lineEdit_MTTRi_2")
        self.gridLayout_3.addWidget(self.lineEdit_MTTRi_2, 7, 3, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem15, 7, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 5, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 7, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 2, 1, 1)
        self.tabWidget.addTab(self.Component2, "")
        self.Component3 = QtWidgets.QWidget()
        self.Component3.setObjectName("Component3")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.Component3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 20, 331, 411))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem16 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem16, 1, 1, 1, 1)
        self.lineEdit_Ma_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_Ma_3.setObjectName("lineEdit_Ma_3")
        self.gridLayout_5.addWidget(self.lineEdit_Ma_3, 1, 3, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem17, 3, 1, 1, 1)
        self.lineEdit_Mb_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_Mb_3.setObjectName("lineEdit_Mb_3")
        self.gridLayout_5.addWidget(self.lineEdit_Mb_3, 2, 3, 1, 1)
        self.lineEdit_L_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_L_3.setText("")
        self.lineEdit_L_3.setObjectName("lineEdit_L_3")
        self.gridLayout_5.addWidget(self.lineEdit_L_3, 0, 3, 1, 1)
        self.lineEdit_mud_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_mud_3.setObjectName("lineEdit_mud_3")
        self.gridLayout_5.addWidget(self.lineEdit_mud_3, 3, 3, 1, 1)
        self.lineEdit_mub_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_mub_3.setObjectName("lineEdit_mub_3")
        self.gridLayout_5.addWidget(self.lineEdit_mub_3, 4, 3, 1, 1)
        self.lineEdit_c1_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_c1_3.setObjectName("lineEdit_c1_3")
        self.gridLayout_5.addWidget(self.lineEdit_c1_3, 5, 3, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem18, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 6, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem19, 4, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 3, 2, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem20, 2, 1, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem21, 5, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 2, 2, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem22, 6, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 4, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 0, 2, 1, 1)
        self.lineEdit_c0_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_c0_3.setObjectName("lineEdit_c0_3")
        self.gridLayout_5.addWidget(self.lineEdit_c0_3, 6, 3, 1, 1)
        self.lineEdit_MTTRi_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_MTTRi_3.setObjectName("lineEdit_MTTRi_3")
        self.gridLayout_5.addWidget(self.lineEdit_MTTRi_3, 7, 3, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem23, 7, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 5, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 7, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 1, 2, 1, 1)
        self.tabWidget.addTab(self.Component3, "")
        self.Component4 = QtWidgets.QWidget()
        self.Component4.setObjectName("Component4")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.Component4)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 20, 331, 411))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem24 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem24, 1, 1, 1, 1)
        self.lineEdit_Ma_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_Ma_4.setObjectName("lineEdit_Ma_4")
        self.gridLayout_6.addWidget(self.lineEdit_Ma_4, 1, 3, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem25, 3, 1, 1, 1)
        self.lineEdit_Mb_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_Mb_4.setObjectName("lineEdit_Mb_4")
        self.gridLayout_6.addWidget(self.lineEdit_Mb_4, 2, 3, 1, 1)
        self.lineEdit_L_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_L_4.setText("")
        self.lineEdit_L_4.setObjectName("lineEdit_L_4")
        self.gridLayout_6.addWidget(self.lineEdit_L_4, 0, 3, 1, 1)
        self.lineEdit_mud_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_mud_4.setObjectName("lineEdit_mud_4")
        self.gridLayout_6.addWidget(self.lineEdit_mud_4, 3, 3, 1, 1)
        self.lineEdit_mub_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_mub_4.setObjectName("lineEdit_mub_4")
        self.gridLayout_6.addWidget(self.lineEdit_mub_4, 4, 3, 1, 1)
        self.lineEdit_c1_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_c1_4.setObjectName("lineEdit_c1_4")
        self.gridLayout_6.addWidget(self.lineEdit_c1_4, 5, 3, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem26, 0, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 6, 2, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem27, 4, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 3, 2, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem28, 2, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem29, 5, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_31.setObjectName("label_31")
        self.gridLayout_6.addWidget(self.label_31, 2, 2, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem30, 6, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_32.setObjectName("label_32")
        self.gridLayout_6.addWidget(self.label_32, 4, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_33.setObjectName("label_33")
        self.gridLayout_6.addWidget(self.label_33, 0, 2, 1, 1)
        self.lineEdit_c0_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_c0_4.setObjectName("lineEdit_c0_4")
        self.gridLayout_6.addWidget(self.lineEdit_c0_4, 6, 3, 1, 1)
        self.lineEdit_MTTRi_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_MTTRi_4.setObjectName("lineEdit_MTTRi_4")
        self.gridLayout_6.addWidget(self.lineEdit_MTTRi_4, 7, 3, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem31, 7, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 5, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_35.setObjectName("label_35")
        self.gridLayout_6.addWidget(self.label_35, 7, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 1, 2, 1, 1)
        self.tabWidget.addTab(self.Component4, "")
        self.SelectFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.SelectFileButton.setGeometry(QtCore.QRect(20, 10, 151, 41))
        self.SelectFileButton.setObjectName("SelectFileButton")
        self.RunButton = QtWidgets.QPushButton(self.centralwidget)
        self.RunButton.setGeometry(QtCore.QRect(220, 10, 121, 41))
        self.RunButton.setObjectName("RunButton")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(30, 80, 321, 121))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem32 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem32, 1, 1, 1, 1)
        self.lineEdit_Epsilon = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_Epsilon.setObjectName("lineEdit_Epsilon")
        self.gridLayout_4.addWidget(self.lineEdit_Epsilon, 1, 3, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem33, 2, 1, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem34, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 0, 2, 1, 1)
        self.lineEdit_Budget = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_Budget.setObjectName("lineEdit_Budget")
        self.gridLayout_4.addWidget(self.lineEdit_Budget, 0, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 1, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 2, 2, 1, 1)
        self.lineEdit_Components = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_Components.setObjectName("lineEdit_Components")
        self.gridLayout_4.addWidget(self.lineEdit_Components, 2, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(50, 60, 47, 13))
        self.label_17.setObjectName("label_17")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(420, 560, 661, 121))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(400, 20, 681, 511))
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(20, 10, 631, 481))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.plotGrid_1 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.plotGrid_1.setContentsMargins(0, 0, 0, 0)
        self.plotGrid_1.setObjectName("plotGrid_1")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(20, 10, 631, 481))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.plotGrid_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.plotGrid_2.setContentsMargins(0, 0, 0, 0)
        self.plotGrid_2.setObjectName("plotGrid_2")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(20, 10, 631, 481))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.plotGrid_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.plotGrid_3.setContentsMargins(0, 0, 0, 0)
        self.plotGrid_3.setObjectName("plotGrid_3")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(430, 540, 91, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(430, 0, 91, 16))
        self.label_38.setObjectName("label_38")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Reliability"))
        self.label_7.setText(_translate("MainWindow", "Operating Cost (c0)"))
        self.label_4.setText(_translate("MainWindow", "B-Mode Fix-Effectiveness Factor (mud)"))
        self.label_3.setText(_translate("MainWindow", "B-Mode Failure Rate (Mb)"))
        self.label_5.setText(_translate("MainWindow", "Cost Increment (mub)"))
        self.label.setText(_translate("MainWindow", "Total Time (L)"))
        self.label_18.setText(_translate("MainWindow", "Replacement Cost (c1)"))
        self.label_8.setText(_translate("MainWindow", "Mean Time to Repair (MTTRi)"))
        self.label_2.setText(_translate("MainWindow", "A-Mode Failure Rate (Ma)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Component1), _translate("MainWindow", "Component 1"))
        self.label_9.setText(_translate("MainWindow", "Operating Cost (c0)"))
        self.label_6.setText(_translate("MainWindow", "B-Mode Fix-Effectiveness Factor (mud)"))
        self.label_10.setText(_translate("MainWindow", "B-Mode Failure Rate (Mb)"))
        self.label_11.setText(_translate("MainWindow", "Cost Increment (mub)"))
        self.label_12.setText(_translate("MainWindow", "Total Time (L)"))
        self.label_19.setText(_translate("MainWindow", "Replacement Cost (c1)"))
        self.label_13.setText(_translate("MainWindow", "Mean Time to Repair (MTTRi)"))
        self.label_14.setText(_translate("MainWindow", "A-Mode Failure Rate (Ma)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Component2), _translate("MainWindow", "Component 2"))
        self.label_15.setText(_translate("MainWindow", "Operating Cost (c0)"))
        self.label_16.setText(_translate("MainWindow", "B-Mode Fix-Effectiveness Factor (mud)"))
        self.label_20.setText(_translate("MainWindow", "B-Mode Failure Rate (Mb)"))
        self.label_23.setText(_translate("MainWindow", "Cost Increment (mub)"))
        self.label_25.setText(_translate("MainWindow", "Total Time (L)"))
        self.label_26.setText(_translate("MainWindow", "Replacement Cost (c1)"))
        self.label_27.setText(_translate("MainWindow", "Mean Time to Repair (MTTRi)"))
        self.label_28.setText(_translate("MainWindow", "A-Mode Failure Rate (Ma)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Component3), _translate("MainWindow", "Component 3"))
        self.label_29.setText(_translate("MainWindow", "Operating Cost (c0)"))
        self.label_30.setText(_translate("MainWindow", "B-Mode Fix-Effectiveness Factor (mud)"))
        self.label_31.setText(_translate("MainWindow", "B-Mode Failure Rate (Mb)"))
        self.label_32.setText(_translate("MainWindow", "Cost Increment (mub)"))
        self.label_33.setText(_translate("MainWindow", "Total Time (L)"))
        self.label_34.setText(_translate("MainWindow", "Replacement Cost (c1)"))
        self.label_35.setText(_translate("MainWindow", "Mean Time to Repair (MTTRi)"))
        self.label_36.setText(_translate("MainWindow", "A-Mode Failure Rate (Ma)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Component4), _translate("MainWindow", "Component 4"))
        self.SelectFileButton.setText(_translate("MainWindow", "Select xls File"))
        self.RunButton.setText(_translate("MainWindow", "RUN"))
        self.lineEdit_Epsilon.setText(_translate("MainWindow", "0.001"))
        self.label_21.setText(_translate("MainWindow", "Budget"))
        self.lineEdit_Budget.setText(_translate("MainWindow", "1000000000"))
        self.label_22.setText(_translate("MainWindow", "Epsilon"))
        self.label_24.setText(_translate("MainWindow", "Components"))
        self.lineEdit_Components.setText(_translate("MainWindow", "2"))
        self.label_17.setText(_translate("MainWindow", "Globals"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Reliability-Availability"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Reliability-Fleet Size"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Availability-Fleet Size"))
        self.label_37.setText(_translate("MainWindow", "Results Table"))
        self.label_38.setText(_translate("MainWindow", "Results Graphs"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

